name: "Teste_Fabrica_RDP"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: "1. Preparar Senha"
        shell: powershell
        run: |
          $p = "${{ secrets.otimizacao2 }}"
          net user runneradmin $p
          # Garante que o usuário tenha permissão de acesso remoto
          net localgroup "Remote Desktop Users" runneradmin /add

      - name: "2. Habilitar RDP Padrão"
        shell: powershell
        run: |
          # Ativa o RDP e mantém a NLA de fábrica
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: "3. Instalar e Abrir Túnel"
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "C:\cloudflared.exe"
          # Inicia o túnel gravando o log para extrair o link
          Start-Process -FilePath "C:\cloudflared.exe" -ArgumentList "tunnel --url rdp://127.0.0.1:3389" -RedirectStandardError "v_log.txt"

      - name: "4. Exibir Link de Acesso"
        shell: powershell
        run: |
          $ep = ""
          while (!$ep) {
            Start-Sleep -Seconds 5
            if (Test-Path "v_log.txt") {
              $log = Get-Content "v_log.txt"
              $ep = $log | Select-String -Pattern "https://.*\.trycloudflare\.com" | ForEach-Object { $_.Matches.Value }
            }
          }
          $cleanLink = $ep.Replace("https://", "")
          Write-Host "----------------------------------------------"
          Write-Host "ENDERECO RDP: $cleanLink"
          Write-Host "USUARIO: runneradmin"
          Write-Host "----------------------------------------------"
          # Mantém rodando por 6 horas
          Start-Sleep -Seconds 21600
