name: "Clean_Test_RDP"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: "Fluxo_01: Preparação"
        uses: actions/checkout@v4

      - name: "Fluxo_02: Configuração de Rede e RDP"
        shell: powershell
        run: |
          # Define a senha do administrador
          $p = "${{ secrets.otimizacao2 }}"
          net user runneradmin $p
          
          # Força a liberação do RDP e mata o erro 0x904 (NLA)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 1
          
          # Abre o firewall
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Reinicia o serviço para aplicar as mudanças agora
          Restart-Service TermService -Force
          
          # Baixa o Cloudflared
          Start-BitsTransfer -Source "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -Destination "C:\cloudflared.exe"

      - name: "Fluxo_03: Iniciar Túnel"
        shell: powershell
        run: |
          Start-Sleep -Seconds 5
          Start-Process -FilePath "C:\cloudflared.exe" -ArgumentList "tunnel --url rdp://127.0.0.1:3389" -RedirectStandardError "v_log.txt"

      - name: "Fluxo_04: Gerar Link e Manter Ativo"
        shell: powershell
        run: |
          $ep = ""
          while (!$ep) {
            Start-Sleep -Seconds 3
            if (Test-Path "v_log.txt") {
              $log = Get-Content "v_log.txt"
              $ep = $log | Select-String -Pattern "https://.*\.trycloudflare\.com" | ForEach-Object { $_.Matches.Value }
            }
          }
          Write-Host "----------------------------------------------"
          Write-Host "LINK RDP: $ep"
          Write-Host "USUARIO: runneradmin"
          Write-Host "----------------------------------------------"
          # Mantém a máquina ligada por 6 horas
          Start-Sleep -Seconds 21600
